server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:xe;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: H2
  h2:
    console:
      enabled: true
  application:
    name: database-sink
  sleuth.sampler.percentage: 1
  cloud:
    stream:
      jms.ibmmq:
        host: localhost
        port: 1416
        queueManager: testDev
        channel: troll.SVRCONN
        transportType: 1
        binder:
          default-destination-type: queue

      bindings:
        input:
          destination: TROLL.MESSAGE.PROCESSOR
        database:
          destination: TROLL.DATABASE
